# Generated by Django 5.1.6 on 2025-05-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_formulairecharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulairecharge',
            name='date_payement',
            field=models.DateField(verbose_name='Date Payement'),
        ),
    ]
