# Generated by Django 5.1.6 on 2025-05-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_formulairecharge_date_payement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiffreAffaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (MAD)')),
            ],
            options={
                'verbose_name': "Chiffre d'affaire",
                'verbose_name_plural': "Chiffres d'affaires",
                'unique_together': {('annee',)},
            },
        ),
    ]
