# Generated by Django 5.1.6 on 2025-05-31 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_chiffreaffaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulairecharge',
            name='date_facture',
        ),
        migrations.AddField(
            model_name='formulairecharge',
            name='date_facture_au',
            field=models.DateField(blank=True, null=True, verbose_name='Date Facture Au'),
        ),
        migrations.AddField(
            model_name='formulairecharge',
            name='date_facture_du',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Date Facture Du'),
            preserve_default=False,
        ),
    ]
